spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/woodo-homework
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  config:
    activate:
      on-profile: db-local

---

# H2 Database
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    activate:
      on-profile: db-h2
